server:
  context-path: /auth
  port: 5000

management:
  security:
    enabled: false
  context-path: /mgmt

eureka:
  instance:
    metadata-map:
      management:
        context-path: ${server.context-path}/actuator
    health-check-url-path: ${server.context-path}/actuator/health
    status-page-url-path: ${server.context-path}/actuator/info
      home-page-url: http://localhost:${server.port}/

spring:
  datasource:
    url: jdbc:h2:mem:user
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
