server:
  context-path: /auth
  port: 5000

management:
  security:
    enabled: false
  context-path: /mgmt


spring:
  datasource:
    url: jdbc:h2:mem:user
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
