spring:
  application:
    name: zipkin
  rabbitmq:
    host: rabbitmq
    username: admin
    password: admin
    port: 5672
  security:
    user:
      name: admin
      password: ${ZIPKIN_SERVER_PASSWORD:admin}
server:
  port: 9411


